/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schn27.arinc429tester.ui;

/**
 *
 * @author amalikov
 */
public class ConverterDialog extends javax.swing.JDialog {

	/**
	 * Creates new form CalcDialog
	 */
	public ConverterDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        signBit = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        HiBit = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        loBit = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        hiBitValue = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        btnCode = new javax.swing.JButton();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JButton jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data convertor");
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 0, 10));

        jLabel1.setText("Label");
        jPanel1.add(jLabel1);

        label.setEditable(false);
        label.setToolTipText("");
        jPanel1.add(label);

        jLabel2.setText("Sign bit");
        jPanel1.add(jLabel2);

        signBit.setToolTipText("");
        jPanel1.add(signBit);

        jLabel3.setText("Hi bit");
        jPanel1.add(jLabel3);

        HiBit.setToolTipText("");
        jPanel1.add(HiBit);

        jLabel4.setText("Lo bit");
        jPanel1.add(jLabel4);

        loBit.setToolTipText("");
        jPanel1.add(loBit);

        jLabel5.setText("Hi bit value");
        jPanel1.add(jLabel5);

        hiBitValue.setToolTipText("");
        jPanel1.add(hiBitValue);

        jLabel6.setText("Code");
        jPanel1.add(jLabel6);

        btnCode.setText("Complement");
        jPanel1.add(btnCode);

        jButton1.setText("OK");

        jButton2.setText("Disable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HiBit;
    private javax.swing.JButton btnCode;
    private javax.swing.JTextField hiBitValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField label;
    private javax.swing.JTextField loBit;
    private javax.swing.JTextField signBit;
    // End of variables declaration//GEN-END:variables
}
